config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'login_guest', to: 'sessions#create_guest'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :edit_account
      get :edit_profile
      get :posts
      get :search#できればusers/:id/posts/searchというurlにしたいが..
      post :create
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :microposts, only: [:show, :create, :destroy]do
    member do
      get :search
    end
  end
  
  resources :topics, only: [:index, :create, :destroy]do
    collection do
      get :search
    end
  end
  
  resources :favorites, only: [:create, :destroy]
  
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  validates :age, numericality: { only_integer: true, allow_nil: true }
  
  #カラムの名前をmount_uploaderに指定
  mount_uploader :image, ImageUploader
  
  has_many :microposts
  has_many :topics
  
  #お気に入り関連
  has_many :favorites
  has_many :likes, through: :favorites, source: :topic
  def favorite(topic)
      self.favorites.create(topic_id: topic.id)
  end
  
  def unfavorite(topic)
      favorite = self.favorites.find_by(topic_id: topic.id)
      favorite.destroy if favorite
  end
  
  def likes?(topic)
      self.likes.include?(topic)
  end
  
  #リレーションシップ関連
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :followings, :followers, :edit_profile,  :edit_account, :posts, :search,]
  before_action :correct_user, only: [:edit_account, :edit_profile]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end
  
  def edit_account
    @user = User.find(params[:id])
  end
  
  def edit_profile
    @user = User.find(params[:id])
  end
  
  def update
    @path = Rails.application.routes.recognize_path(request.referer)
    @user = User.find(params[:id])
    #アカウント変更
    if @path[:action] == "edit_account"
      if @user.update(user_params)
        flash[:success] = '登録内容を変更しました'
        redirect_to @user
      else
        flash.now[:danger] = '登録内容の変更に失敗しました'
        render :edit_account
      end
    #プロフィール編集
    else
      if @user.update(user_params2)
        flash[:success] = '編集しました'
        redirect_to @user
      else
        flash.now[:danger] = '編集に失敗しました'
        render :edit_profile
      end
    end
  end

  def create
    @path = Rails.application.routes.recognize_path(request.referer)
    #個人コミュニティからの投稿
    if (@path[:action] == "posts") or (@path[:action] == "search")
      @topic = Topic.find_by(user_id: params[:id], flag: 1)
      @micropost = @topic.microposts.build(micropost_params)
      @path = Rails.application.routes.recognize_path(request.referer)
      if @micropost.save
        flash[:success] = 'メッセージを投稿しました。'
        redirect_to posts_user_url(@topic.user_id)
      else
        #render処理をするとurlが変わってしまいその影響で再度createするとエラーになってしまう(原因不明どうにかしたい)
        # @microposts = @topic.microposts.order(id: :desc).page(params[:page])
        # @user = User.find(params[:id])#card表示に必要
        # flash.now[:danger] = 'メッセージの投稿に失敗しました。'
        # render 'users/posts&search'
        flash[:danger] = 'メッセージの投稿に失敗しました。'
        redirect_to posts_user_url(@topic.user_id)
      end
    #アカウントの登録
    else
      @user = User.new(user_params)
      @user.topics.build(title: "#{@user.name}のコミュニティ", flag: 1)
      if @user.save
        session[:user_id] = @user.id
        flash[:success] = 'ユーザを登録し、ログインしました。'
        redirect_to topics_url
      else
        flash.now[:danger] = 'ユーザの登録に失敗しました。'
        render :new
      end
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  def posts
    @user = User.find(params[:id])#card表示に必要
    @topic = Topic.find_by(user_id: params[:id], flag: 1)
    @micropost = @topic.microposts.build
    counts(@user)
    @microposts = @topic.microposts.order(id: :desc).page(params[:page])
    render "posts&search"
  end
  
  def search
    @user = User.find(params[:id])#card表示に必要
    @topic = Topic.find_by(user_id: params[:id], flag: 1)
    @micropost = @topic.microposts.build
    if params[:keyword] == 'new'
      @microposts = @topic.microposts.order(id: :desc).page(params[:page])
    else #old
      @microposts = @topic.microposts.order(id: :asc).page(params[:page])
    end
    render "posts&search"
  end
  
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def user_params2
    params.require(:user).permit(:content, :sex, :age, :address, :content2, :content3, :content4, :image)
  end

  def micropost_params
    params.require(:micropost).permit(:content,:image,:youtube_url).merge(user_id: current_user.id)
  end

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
    <a class="card mb-3 shadow-lg text-dark" href="<%= user_path(user) %>" style="text-decoration: none; border-left-width:8px" onMouseOut="this.style.opacity='1'" onMouseOver="this.style.opacity='0.5'">
      <li class="media">
        <!--ユーザ画像-->
        <% if user.image? %>
          <%= image_tag user.image.url, class: 'rounded img-fluid mr-2', size: '60', alt: "ユーザ画像"  %>
        <% else %>
          <%= image_tag "no-image.jpg", class: 'rounded img-fluid mr-2', size: '60', alt: "デフォルト画像" %>
        <% end %>
        <!--ユーザ名とコメント-->
        <div class="media-body">
          <h2><%= user.name %></h2>
          <p><%= user.content %></p>
        </div>
      </li>
    </a>
    <% end %>
  </ul>
  <%= paginate users %>
<% else %>
  <p>登録されているユーザはいません</p>
<% end %>

app/views/users/edit_account.html.erb
<div class="text-center">
  <h1 class="subtitle pt-3">アカウント編集</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, '名前', :class => "border-bottom" %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, 'メールアドレス', :class => "border-bottom" %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, 'パスワード', :class => "border-bottom" %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード(確認)', :class => "border-bottom"%>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <%= f.submit '更新', class: 'btn rounded-pill btn-primary btn-block' %>
    <% end %>
    
  </div>
</div>

app/views/users/edit_profile.html.erb
<h1 class="mb-4 pt-3 subtitle"><%= @user.name %>のページ</h1>
<%= form_with(model: @user, local: true) do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
<div class="row">
  <aside class="col-sm-4">
    <div class="card userIconWaku">
      <div class="card-header text-light">
        <h3 class="card-title d-inline"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <% if @user.image? %>
          <%= image_tag @user.image.url, class: 'rounded img-fluid', size: '500', alt: "ユーザ画像" %>
        <% else %>
          <%= image_tag "no-image.jpg", class: 'rounded img-fluid', size: '500', alt: "デフォルト画像" %>
        <% end %>
        <%= f.file_field :image, :style => "font-size:12px;" %>
      </div>
    </div>
    <%= f.submit '更新する', class: 'btn btn-block btn-primary rounded-pill mt-2' %>
  </aside>

  <div class="col-sm-8">
    
     <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= posts_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(posts_user_path(@user)) %>">コミュニティ</a></li>
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(edit_profile_user_path(@user)) %>">プロフィール(編集中) </a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー<span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー<span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
      
      
    <table class="table table-striped table-bordered">
      <tbody>

      <tr>
        <td colspan="2">自己紹介</td>
      </tr>
      <tr>
        <td colspan="2"><%= f.text_area :content, :class => "form-control" %></td>
      </tr>
      
      <tr>
        <td>性別</td>
        <td>年齢<span style="font-size:3px;">※半角数値で入力してください</span></td>
      </tr>

      <tr>
        <td><%= f.select :sex, [['非公開', '0'],['男性', '1'],['女性', '2']] ,{selected: @user.sex}, { class: 'form-control'} %></td>
        <td><%= f.text_field :age, :class => 'form-control' %></td>
      </tr>

      <tr>
        <td colspan="2">居住地</td>
      </tr>
      <tr>
        <td colspan="2"><%= f.text_field :address, :class => "form-control" %></td>
      </tr>
      
      <tr>
        <td colspan="2">プレイしている音ゲー</td>
      </tr>
      <tr>
        <td colspan="2"><%= f.text_area :content2, :class => "form-control" %></td>
      </tr>
      
      <tr>
        <td colspan="2">プレイ環境</td>
      </tr>
      <tr>
        <td colspan="2"><%= f.text_area :content3, :class => "form-control" %></td>
      </tr>
      
      <tr>
        <td colspan="2">好きな楽曲・譜面</td>
      </tr>
      <tr>
        <td colspan="2"><%= f.text_area :content4, :class => "form-control" %></td>
      </tr>
      
      </tbody>
    </table>
    
  </div>
  
</div>
<% end %>

app/views/users/followers.html.erb
<h1 class="mb-4 pt-3 subtitle"><%= @user.name %>のページ</h1>
<div class="row">
  
  <aside class="col-sm-4">
    <div class="card userIconWaku mb-2">
      <div class="card-header text-light">
        <h3 class="card-title d-inline"><%= @user.name %></h3>
        <%= render 'relationships/follow_button', user: @user %>
      </div>
      <div class="card-body">
        <% if @user.image? %>
          <%= image_tag @user.image.url, class: 'rounded img-fluid', size: '500', alt: "ユーザ画像"  %>
        <% else %>
          <%= image_tag "no-image.jpg", class: 'rounded img-fluid', size: '500', alt: "デフォルト画像" %>
        <% end %> 
      </div>
    </div>
  </aside>
  
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= posts_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(posts_user_path(@user)) %>">コミュニティ  </a></li>
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">プロフィール  </a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render 'users', users: @followers %>
  </div>
  
</div>

app/views/users/followings.html.erb
<h1 class="mb-4 pt-3 subtitle"><%= @user.name %>のページ</h1>
<div class="row">
  
  <aside class="col-sm-4">
    <div class="card userIconWaku mb-2">
      <div class="card-header text-light">
        <h3 class="card-title d-inline"><%= @user.name %></h3>
        <%= render 'relationships/follow_button', user: @user %>
      </div>
      <div class="card-body">
        <% if @user.image? %>
          <%= image_tag @user.image.url, class: 'rounded img-fluid', size: '500', alt: "ユーザ画像"  %>
        <% else %>
          <%= image_tag "no-image.jpg", class: 'rounded img-fluid', size: '500', alt: "デフォルト画像" %>
        <% end %> 
      </div>
    </div>
  </aside>
  
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= posts_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(posts_user_path(@user)) %>">コミュニティ</a></li>
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">プロフィール</a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー<span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー<span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render 'users', users: @followings %>
  </div>
  
</div>

app/views/users/index.html.erb
<h1 class="mb-4 pt-3 subtitle">ユーザ一覧</h1>
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1 class="subtitle mt-3">新規登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, '名前', :class => "border-bottom" %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, 'メールアドレス', :class => "border-bottom" %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, 'パスワード', :class => "border-bottom" %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード(確認)', :class => "border-bottom" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <%= f.submit '作成', class: 'btn rounded-pill btn-primary btn-block' %>
    <% end %>
    
  </div>
</div>

app/views/users/posts&search.html.erb
<h1 class="mb-4 pt-3 subtitle"><%= @user.name %>のページ</h1>
<div class="row">
  <div class="col-sm-4">
    
    <aside>
      <div class="card mb-3 userIconWaku">
        <div class="card-header text-light">
          <h3 class="card-title d-inline"><%= @user.name %></h3>
          <%= render 'relationships/follow_button', user: @user %>
        </div>
        <div class="card-body">
        <% if @user.image? %>
          <%= image_tag @user.image.url, class: 'rounded img-fluid', size: '500', alt: "ユーザ画像"  %>
        <% else %>
          <%= image_tag "no-image.jpg", class: 'rounded img-fluid', size: '500', alt: "デフォルト画像" %>
        <% end %> 
        </div>
      </div>
    </aside>
    
    <aside class="p-3 waku3 form-group PC">
      <%= form_with(model: @micropost, url: user_path, method: :post, local: true) do |f| %>
        <%= f.text_area :content, class: 'form-control', rows: 5 %>
        <!--「@micropost.topic_id」をパラメータとしてmicroposts#CREATEに渡す処理-->
        <%= f.hidden_field :topic_id, :value => @micropost.topic_id %>
        <%= f.file_field :image, :style => "font-size:12px"; %>
        <%= f.text_field :youtube_url, class: 'form-control', placeholder: 'youtube_url' %>
        <%= f.submit '投稿', class: 'btn btn-block rounded-pill btn-primary' %>
      <% end %>
    </aside>
      
    <aside class="p-3 waku4 form-group PC">
      <%= form_with(url: search_user_path(id: @topic.user_id), method: :get, local: true) do |f| %>
        <%= f.select :keyword, [['投稿日が新しい順', 'new'],['投稿日が古い順', 'old']] ,{selected: params[:keyword]}, { class: 'form-control'}%>
        <%= f.submit '更新', class: 'btn btn-block btn-primary rounded-pill' %>
      <% end %>
    </aside>
    
  </div>
  
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
    　<li class="nav-item"><a href="<%= posts_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(posts_user_path(@user)) %>">コミュニティ</a></li>
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">プロフィール</a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー<span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー<span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    
    <p>※コミュニティ一覧には表示されない<%= @user.name %>独自のコミュニティです。</p>

<!--スマホの場合のみ表示-->
    <aside class="p-3 waku3 form-group SF" style="display:none;">
      <%= form_with(model: @micropost, url: user_path, method: :post, local: true) do |f| %>
        <%= f.text_area :content, class: 'form-control', rows: 5 %>
        <!--「@micropost.topic_id」をパラメータとしてmicroposts#CREATEに渡す処理-->
        <%= f.hidden_field :topic_id, :value => @micropost.topic_id %>
        <%= f.file_field :image, :style => "font-size:12px"; %>
        <%= f.text_field :youtube_url, class: 'form-control', placeholder: 'youtube_url' %>
        <%= f.submit '投稿', class: 'btn btn-block rounded-pill btn-primary' %>
      <% end %>
    </aside>
      
    <aside class="p-3 waku4 form-group SF" style="display:none;">
      <%= form_with(url: search_user_path(id: @topic.user_id), method: :get, local: true) do |f| %>
        <%= f.select :keyword, [['投稿日が新しい順', 'new'],['投稿日が古い順', 'old']] ,{selected: params[:keyword]}, { class: 'form-control'}%>
        <%= f.submit '更新', class: 'btn btn-block btn-primary rounded-pill' %>
      <% end %>
    </aside>
<!--スマホの場合のみ表示(終わり)-->

    <ul class="list-unstyled waku5 pl-3">
    
      <% if !@microposts.any? %>
        何も投稿されていません
      <% end %>
      
      <% @microposts.each do |micropost| %>
      <li class="balloon mb-0 mt-2">
        <!--ユーザ画像の表示-->
        <% if micropost.user.image? && micropost.delete_frag != 1 %>
          <%= image_tag micropost.user.image.url, class: 'rounded img-fluid mr-3', size: '40', alt: "ユーザ画像"  %>
        <% else %>
          <%= image_tag "no-image.jpg", class: 'rounded img-fluid mr-3', size: '40', alt: "デフォルト画像" %>
        <% end %>
      
        <div class="says"> 
          <!--投稿が削除されている場合-->
          <% if micropost.delete_frag == 1 %>
            <p>投稿が削除されています</p>
          <% else %>
          
            <div>
              <div class="d-inline">
                <!--ユーザ名  ・ログインユーザと投稿者が一致する場合-->
                <% if current_user == micropost.user %>
                  <%= link_to micropost.user.name, user_path(micropost.user) , :class => "current-author" %> 
                  <span class="text-muted" style="font-size:5px;">投稿日:<%= micropost.created_at.strftime('%Y/%m/%d %H:%M') %></span>
                <% else %>
                  <%= link_to micropost.user.name, user_path(micropost.user) %> 
                  <span class="text-muted" style="font-size:5px;">投稿日:<%= micropost.created_at.strftime('%Y/%m/%d %H:%M') %></span>
                <% end %>
               
                <!--ごみ箱ボタン-->
                <% if current_user == micropost.user %>
                  <%= link_to micropost, :method => :delete , data: { confirm: "本当に削除しますか?" } do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                <% end %>
              </div>
              <div class="d-block">
                <!--文字の投稿-->
                <% if micropost.content? %>
                 <p style="white-space:pre-line"><%= micropost.content %></p>
                <% end %>
                
                <!--画像の投稿-->
                <% if micropost.image? %>
                  <%= image_tag micropost.image.url, class: 'img-fluid', size: '250', alt: "投稿画像"  %>
                <% end %>
                
                 <!--YouTubeの投稿-->
                <% if micropost.youtube_url? %>
                  <iframe src="https://www.youtube.com/embed/<%= micropost.youtube_url[32..42] %>", allow= "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", allowfullscreen="", frameborder="0", height="250", width="100%"></iframe> </iframe>
                <% end %>
              </div>
            </div>
            
          <% end %>
        </div> 
      </li>
      <% end %>
      <%= paginate @microposts %>
    </ul>
  </div>
  
</div>

app/views/users/show.html.erb
<h1 class="mb-4 pt-3 subtitle"><%= @user.name %>のページ</h1>
<div class="row">
  
  <aside class="col-sm-4">
    <div class="card userIconWaku">
      <div class="card-header text-light">
        <h3 class="card-title d-inline"><%= @user.name %></h3>
        <%= render 'relationships/follow_button', user: @user %>
      </div>
      <div class="card-body">
        <% if @user.image? %>
          <%= image_tag @user.image.url, class: 'rounded img-fluid', size: '500', alt: "ユーザ画像"  %>
        <% else %>
          <%= image_tag "no-image.jpg", class: 'rounded img-fluid', size: '500', alt: "デフォルト画像" %>
        <% end %>  
      </div>
    </div>
    <% if current_user == @user %>
      <%= link_to "プロフィール編集", edit_profile_user_path, class: 'btn  btn-block btn-primary rounded-pill mt-2' %> 
      <%= link_to "アカウント編集", edit_account_user_path, class: 'btn  btn-block btn-primary rounded-pill mb-2' %> 
    <% end %>
  </aside>

  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= posts_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(posts_user_path(@user)) %>">コミュニティ </a></li>
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">プロフィール </a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    
    <table class="table table-striped table-bordered">
      <tbody>

      <tr>
        <td colspan="2">自己紹介</td>
      </tr>
      <tr>
        <td colspan="2"><%= @user.content %></td>
      </tr>


      <tr>
        <td>性別</td>
        <td>年齢</td>
      </tr>

      <tr>
        <td>    
          <% if @user.sex == 1 %>
            男性
          <% elsif @user.sex == 2 %>
            女性
          <% else %>
            非公開
          <% end %>
        </td>
        <td>
          <% if @user.age? %>
            <%= @user.age %>
          <% else %>
            非公開
          <% end %>
        </td>
      </tr>

      <tr>
        <td colspan="2">居住地</td>
      </tr>
      <tr>
        <td colspan="2"><%= @user.address %></td>
      </tr>
      
      <tr>
        <td colspan="2">プレイしている音ゲー</td>
      </tr>
      <tr>
        <td colspan="2"><%= @user.content2 %></td>
      </tr>
      
      
      <tr>
        <td colspan="2">プレイ環境</td>
      </tr>
      <tr>
        <td colspan="2"><%= @user.content3 %></td>
      </tr>
      
      <tr>
        <td colspan="2">好きな楽曲・譜面</td>
      </tr>
      <tr>
        <td colspan="2"><%= @user.content4 %></td>
      </tr>
      
      </tbody>
    </table>
    
    
    
    
    
  </div>
  
</div>