config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'login_guest', to: 'sessions#create_guest'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :edit_account
      get :edit_profile
      get :posts
      get :search#できればusers/:id/posts/searchというurlにしたいが..
      post :create
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :microposts, only: [:show, :create, :destroy]do
    member do
      get :search
    end
  end
  
  resources :topics, only: [:index, :create, :destroy]do
    collection do
      get :search
    end
  end
  
  resources :favorites, only: [:create, :destroy]
  
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  
  validates :content, length: { maximum: 255 }
  mount_uploader :image, ImageUploader

  # content,image,youtube_url全てnilだった場合だけ弾く
  validates :content_or_image_or_youtubeurl, presence: true

  private
    def content_or_image_or_youtubeurl
      content.presence or image.presence or youtube_url.presence
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :require_user_logged_in, only: [:create]
  before_action :correct_user_destroy, only: [:destroy]
  
  def show
    @topic = Topic.find_by(id: params[:id]) 
    @micropost = @topic.microposts.build
    @microposts = @topic.microposts.order(id: :desc).page(params[:page])
    render 'microposts/show&search'
  end
  
  def search
    @topic = Topic.find_by(id: params[:id]) 
    @micropost = @topic.microposts.build
    if params[:keyword] == 'new'
      @microposts = @topic.microposts.order(id: :desc).page(params[:page])
    else #old
      @microposts = @topic.microposts.order(id: :asc).page(params[:page])
    end
    render 'microposts/show&search'
  end
  
  def create
    @topic = Topic.find_by(id: params[:micropost][:topic_id]) 
    @micropost = @topic.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = '投稿しました。'
      redirect_to micropost_url(@micropost.topic_id)
    else 
      #render処理をするとurlが変わってしまいその影響で再度createするとエラーになってしまう(原因不明どうにかしたい)
      # @microposts = @topic.microposts.order(id: :desc).page(params[:page])
      # flash.now[:danger] = 'メッセージの投稿に失敗しました。'
      # render 'microposts/show&search'
      flash[:danger] = '投稿に失敗しました。'
      redirect_to micropost_url(@micropost.topic_id)
    end
  end

  def destroy
    @micropost.update(delete_frag: 1)
    if @micropost.save
      flash[:success] = '投稿を削除しました。'
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = '投稿の削除に失敗しました。'
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content,:image,:youtube_url).merge(user_id: current_user.id)
  end

  def correct_user_destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    unless @micropost
      redirect_to root_url
    end
  end
  
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/show&search.html.erb
<% if @topic.tag == 0 %>
　<span class="mt-3 badge badge-secondary">全般</span>
<% elsif @topic.tag == 1 %>
　<span class="mt-3 badge badge-secondary">beatmania</span>
<% elsif @topic.tag == 2 %>
  <span class="mt-3 badge badge-secondary">popn music</span>
<% elsif @topic.tag == 3 %>
  <span class="mt-3 badge badge-secondary">Dance Dance Revolution</span>
<% elsif @topic.tag == 4 %>
  <span class="mt-3 badge badge-secondary">GITADORA</span>
<% elsif @topic.tag == 5 %>
  <span class="mt-3 badge badge-secondary">jubeat</span>
<% elsif @topic.tag == 6 %>
  <span class="mt-3 badge badge-secondary">SOUND VOLTEX</span>
<% elsif @topic.tag == 7 %>
  <span class="mt-3 badge badge-secondary">DANCERUSH STARDOM</span>
<% elsif @topic.tag == 8 %>
  <span class="mt-3 badge badge-secondary">太鼓の達人</span>
<% elsif @topic.tag == 9 %>
  <span class="mt-3 badge badge-secondary">maimai</span>
<% elsif @topic.tag == 10 %>
  <span class="mt-3 badge badge-secondary">CHUNITHM</span>
<% elsif @topic.tag == 11 %>
  <span class="mt-3 badge badge-secondary">オンゲキ</span>
<% elsif @topic.tag == 12 %>
  <span class="mt-3 badge badge-secondary">グルーヴコースター</span>
<% elsif @topic.tag == 13 %>
  <span class="mt-3 badge badge-secondary">WACCA</span>
<% elsif @topic.tag == 14 %>
  <span class="mt-3 badge badge-secondary">Cytus</span>
<% elsif @topic.tag == 15 %>
  <span class="mt-3 badge badge-secondary">Deemo</span>
<% elsif @topic.tag == 16 %>
  <span class="mt-3 badge badge-secondary">VOEZ</span>
<% elsif @topic.tag == 17 %>
  <span class="mt-3 badge badge-secondary">アイドルマスター シンデレラガールズ スターライトステージ</span>
<% elsif @topic.tag == 18 %>
  <span class="mt-3 badge badge-secondary">ラブライブ! スクールアイドルフェスティバル</span>
<% elsif @topic.tag == 19 %>
  <span class="mt-3 badge badge-secondary">バンドリ! ガールズバンドパーティ!</span>
<% elsif @topic.tag == 20 %>
  <span class="mt-3 badge badge-secondary">D4DJ Groovy Mix</span>
<% elsif @topic.tag == 21 %>
  <span class="mt-3 badge badge-secondary">プロジェクトセカイ カラフルステージ! feat.初音ミク</span>
<% elsif @topic.tag == 22 %>
  <span class="mt-3 badge badge-secondary">その他</span>
<% end %>

<h1 class="mb-3 subtitle"><%= @topic.title %></h1>
<div class="row">
  
  <!--画面左側-->
  <div class="col-sm-4">
    <!--投稿項目-->
    <aside class="p-3 waku3 form-group">
      <%= form_with(model: @micropost, local: true) do |f| %>
        <%= f.text_area :content, class: 'form-control', rows: 5 %>
        <!--「@micropost.topic_id」をパラメータとしてmicroposts#CREATEに渡す処理-->
        <%= f.hidden_field :topic_id, :value => @micropost.topic_id %>
        <%= f.file_field :image, :style => "font-size:12px"; %>
        <%= f.text_field :youtube_url, class: 'form-control', placeholder: 'youtube_url' %>
        <!--未ログイン時アラートを鳴らす-->
        <% if logged_in? %>
          <%= f.submit '投稿', class: 'btn btn-block btn-primary rounded-pill' %>
        <% else %>
          <a class="btn btn-block btn-primary rounded-pill" id = "alart" href="#">投稿</a>
        <% end %> 
      <% end %>
    </aside>
    <!--並び替え項目-->
    <aside class="p-3 waku4 form-group">
      <%= form_with(url: search_micropost_path(id: @micropost.topic_id), method: :get, local: true) do |f| %>
        <%= f.select :keyword, [['投稿日が新しい順', 'new'],['投稿日が古い順', 'old']] ,{selected: params[:keyword]}, { class: 'form-control'}%>
        <%= f.submit '更新', class: 'btn btn-block btn-primary rounded-pill'%>
      <% end %>
    </aside>
  </div>
  
  <!--画面右側-->
  <div class="col-sm-8">
    <ul class="list-unstyled waku5 pl-3">
      <% if !@microposts.any? %>
        何も投稿されていません
      <% end %>
        
        
      <% @microposts.each do |micropost| %>
      <li class="balloon mb-0 mt-2">
        <!--ユーザ画像の表示-->
        <% if micropost.user.image? && ( micropost.delete_frag != 1 ) %>
          <%= image_tag micropost.user.image.url, class: 'rounded img-fluid mr-3', size: '40', alt: "ユーザ画像"  %>
        <% else %>
          <%= image_tag "no-image.jpg", class: 'rounded img-fluid mr-3', size: '40', alt: "デフォルト画像" %>
        <% end %> 
        
        <div class="says">
          <!--投稿が削除されている場合-->
          <% if micropost.delete_frag == 1 %>
            <p>投稿が削除されています</p>
          <% else %>
          
            <div><!--下記2つのdivが横並びになるのを防ぐ-->
              <div class="d-inline">
                <!--ユーザ名と投稿日の表示　・ログインユーザと投稿者が一致する場合・ログインはしているけど投稿者と不一致の場合・未ログインの場合-->
                <% if current_user == micropost.user %>
                  <%= link_to micropost.user.name, user_path(micropost.user) , :class => "current-author" %>
                  <span class="text-muted" style="font-size:5px;">投稿日:<%= micropost.created_at.strftime('%Y/%m/%d %H:%M') %></span>
                <% elsif logged_in? %>
                  <%= link_to micropost.user.name, user_path(micropost.user) %> 
                  <span class="text-muted" style="font-size:5px;">投稿日:<%= micropost.created_at.strftime('%Y/%m/%d %H:%M') %></span>
                <% else %>
                  <a id = "alart5" href="#"><%= micropost.user.name %></a>
                  <span class="text-muted" style="font-size:5px;">投稿日:<%= micropost.created_at.strftime('%Y/%m/%d %H:%M') %></span>
                <% end %>
                
                <!--ごみ箱アイコンの表示  -->
                <% if current_user == micropost.user %>
                  <%= link_to micropost, :method => :delete , data: { confirm: "本当に削除しますか?" } do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                <% end %>
              </div>
              <div class="d-block">
                <!--文字の投稿-->
                <% if micropost.content? %>
                  <p style="white-space:pre-line"><%= micropost.content %></p>
                <% end %>
                
                <!--画像の投稿-->
                <% if micropost.image? %>
                  <%= image_tag micropost.image.url, class: 'img-fluid', size: '250', alt: "投稿画像"  %>
                <% end %>
                
                <!--YouTubeの投稿-->
                <% if micropost.youtube_url? %>
                  <iframe src="https://www.youtube.com/embed/<%= micropost.youtube_url[32..42] %>", allow= "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", allowfullscreen="", frameborder="0", height="250", width="100%"></iframe> </iframe>
                <% end %>
              </div>
            </div>
          
          <% end %><!--投稿が削除されている場合-->
        </div><!--class="says"-->
          
      </li><!--class="baloom"-->
      <% end %><!--micropost繰り返し-->
      <%= paginate @microposts %>
        
    </ul><!--class="waku"-->
  </div><!--col右側-->
  
</div><!--row-->


<script>
  $('#alart').click(function() {
    alert('ログインが必要です');
  });
        
  $('#alart5').click(function() {
    alert('ログインが必要です');
  });
</script>