config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'login_guest', to: 'sessions#create_guest'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :edit_account
      get :edit_profile
      get :posts
      get :search#できればusers/:id/posts/searchというurlにしたいが..
      post :create
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :microposts, only: [:show, :create, :destroy]do
    member do
      get :search
    end
  end
  
  resources :topics, only: [:index, :create, :destroy]do
    collection do
      get :search
    end
  end
  
  resources :favorites, only: [:create, :destroy]
  
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="mt-3 alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color:#f4623a; box-shadow: 0px 10px 10px 0px rgba(0,0,0,0.5);" id="mainNav">
    <div class="container">
      <!--ログイン時はコミュニティ一覧画面へ、未ログイン時(ログイン画面と新規登録画面)はトップ画面へ-->
      <% if logged_in? %>
        <%= link_to topics_path , class: 'navbar-brand pt-0 pb-0' do %>
          <%= image_tag "ototudoi.jpg", size: "30x30" %>音集い
        <% end %>
      <% else %>
        <%= link_to root_path, class: 'navbar-brand pt-0 pb-0' do %>
          <%= image_tag "ototudoi.jpg", size: "30x30" %>音集い
        <% end %>
      <% end %>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <% if logged_in? %>
            <li class="nav-item"><%= link_to 'コミュニティ一覧', topics_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'ユーザ一覧', users_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to current_user.name, user_path(current_user), class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
          <% else %>
            <li class="nav-item"><%= link_to 'コミュニティ一覧', topics_path, class: 'nav-link' %></li>
            <li class="nav-item"><a class= 'nav-link' id = "alart1" href="#" >ユーザ一覧</a></li>
            <li class="nav-item"><%= link_to '新規登録', new_user_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
          <% end %>
        </ul>
      </div>
      
    </div>
  </nav>
</header>

<script>
  $('#alart1').click(function() {
    alert('ログインが必要です');
  });
</script>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>音集い</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="icon" type="image/x-icon" href="favicon.ico" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <link rel="stylesheet" href="animate.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <!--<script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>-->
    <!--<script defer src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" integrity="sha384-9/D4ECZvKMVEJ9Bhr3ZnUAF+Ahlagp1cyPC7h5yDlZdXs4DQ/vRftzfd+2uFUuqS" crossorigin="anonymous"></script>-->
    <!--<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">-->
    <!--<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">-->
    <!--<script src="https://kit.fontawesome.com/0775435c1b.js" crossorigin="anonymous"></script>-->
  </head>
  
  <!--ログイン前のトップページにアクセスする場合とそれ以外の場合-->
  <% if ("https://67ad076fa29a461da79cf5a14ef43718.vfs.cloud9.us-east-1.amazonaws.com/" == request.url) or ("https://ototudoi.herokuapp.com/" == request.url) %>
    <%= yield %>
  <% else %>  
    <body class="background-pattern">
      <%= render 'layouts/navbar' %>
      <div class="container bg-white pt-5">
        <%= render 'layouts/flash_messages' %>
        <%= yield %>
      </div>
      <footer class="bg-secondary py-3">
        <div class="container"><div class="small text-center text-light">Copyright © 2021 - ototudoi</div></div>
      </footer>
    </body>
  <% end %>
  
</html>